// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SwimmingApi.Infraestructura.Database;

#nullable disable

namespace SwimmingApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425011126_EliminarIdsDuplicados")]
    partial class EliminarIdsDuplicados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SwimmingApi.Domain.Entities.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("SwimmingApi.Domain.Entities.MarcaDeTiempo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("IdNadador")
                        .HasColumnType("integer");

                    b.Property<int?>("IdNadadorEquipo")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Tiempo")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdNadador");

                    b.HasIndex("IdNadadorEquipo");

                    b.ToTable("MarcasDeTiempo");
                });

            modelBuilder.Entity("SwimmingApi.Domain.Entities.NadadorEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Codigo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("IdEquipo");

                    b.ToTable("NadadoresEquipo");
                });

            modelBuilder.Entity("SwimmingApi.Domain.Entities.Rutina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<bool>("Mostrar")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("SwimmingApi.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("IdEquipo")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdEquipo");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SwimmingApi.Domain.Entities.Entrenador", b =>
                {
                    b.HasBaseType("SwimmingApi.Domain.Entities.Usuario");

                    b.Property<int?>("IdEquipoGestionado")
                        .HasColumnType("integer");

                    b.HasIndex("IdEquipoGestionado");

                    b.HasDiscriminator().HasValue("Entrenador");
                });

            modelBuilder.Entity("SwimmingApi.Domain.Entities.Nadador", b =>
                {
                    b.HasBaseType("SwimmingApi.Domain.Entities.Usuario");

                    b.Property<int?>("IdNadadorEquipo")
                        .HasColumnType("integer");

                    b.HasIndex("IdNadadorEquipo");

                    b.HasDiscriminator().HasValue("Nadador");
                });

            modelBuilder.Entity("SwimmingApi.Domain.Entities.MarcaDeTiempo", b =>
                {
                    b.HasOne("SwimmingApi.Domain.Entities.Nadador", "Nadador")
                        .WithMany("ListaDeTiempo")
                        .HasForeignKey("IdNadador")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SwimmingApi.Domain.Entities.NadadorEquipo", "NadadorEquipo")
                        .WithMany("ListaDeTiempoEquipo")
                        .HasForeignKey("IdNadadorEquipo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Nadador");

                    b.Navigation("NadadorEquipo");
                });

            modelBuilder.Entity("SwimmingApi.Domain.Entities.NadadorEquipo", b =>
                {
                    b.HasOne("SwimmingApi.Domain.Entities.Equipo", "Equipo")
                        .WithMany("ListaNadadores")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("SwimmingApi.Domain.Entities.Rutina", b =>
                {
                    b.HasOne("SwimmingApi.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ListaRutinas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SwimmingApi.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SwimmingApi.Domain.Entities.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("SwimmingApi.Domain.Entities.Entrenador", b =>
                {
                    b.HasOne("SwimmingApi.Domain.Entities.Equipo", "EquipoGestionado")
                        .WithMany()
                        .HasForeignKey("IdEquipoGestionado")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EquipoGestionado");
                });

            modelBuilder.Entity("SwimmingApi.Domain.Entities.Nadador", b =>
                {
                    b.HasOne("SwimmingApi.Domain.Entities.NadadorEquipo", "NadadorEquipo")
                        .WithMany()
                        .HasForeignKey("IdNadadorEquipo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NadadorEquipo");
                });

            modelBuilder.Entity("SwimmingApi.Domain.Entities.Equipo", b =>
                {
                    b.Navigation("ListaNadadores");
                });

            modelBuilder.Entity("SwimmingApi.Domain.Entities.NadadorEquipo", b =>
                {
                    b.Navigation("ListaDeTiempoEquipo");
                });

            modelBuilder.Entity("SwimmingApi.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("ListaRutinas");
                });

            modelBuilder.Entity("SwimmingApi.Domain.Entities.Nadador", b =>
                {
                    b.Navigation("ListaDeTiempo");
                });
#pragma warning restore 612, 618
        }
    }
}
